import { NextResponse } from "next/server";
import OpenAI from "openai";

// ==========================================
// 🔥 GROQ INTERCEPTION 🔥
// Lightning-fast forensic auditing with Llama 3.1 70B
// ==========================================
const groqClient = new OpenAI({ 
  apiKey: process.env.GROQ_API_KEY,
  baseURL: "https://api.groq.com/openai/v1" 
});

export async function POST(req: Request) {
  const startTime = Date.now();

  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;
    const expectedCompany = formData.get("companyName") as string;
    
    if (!file || !expectedCompany) {
      return NextResponse.json({ error: "Missing file or company name" }, { status: 400 });
    }

    console.log(`\n===========================================`);
    console.log(`[SECURE VAULT] Auditing document for: ${expectedCompany}`);

    // 1. Extract text from PDF in RAM
    const arrayBuffer = await file.arrayBuffer();
    const { extractText, getDocumentProxy } = await import("unpdf");
    const pdf = await getDocumentProxy(new Uint8Array(arrayBuffer));
    const { text } = await extractText(pdf, { mergePages: true });
    
    if (!text || text.trim().length === 0) {
      return NextResponse.json({ error: "Empty or unreadable document." }, { status: 400 });
    }

    const cleanedText = text.replace(/\s+/g, ' ').substring(0, 6000);

    // 2. The Advanced Forensic & Deepfake Detection Prompt
    const prompt = `
You are an elite Digital Forensic Auditor specializing in HR fraud and AI-generated document detection.
A candidate uploaded a document claiming employment at "${expectedCompany}".

Document Text:
"""
${cleanedText}
"""

TASK:
1. LEGITIMACY: Does the content convincingly prove employment at ${expectedCompany}? Check for company name context, salary, role, and official language.
2. AI-GENERATION CHECK (DEEPFAKE): Scrutinize the text for signs of synthetic generation:
   - "Robotic Perfection": Overly generic templates with zero human variability.
   - "LLM Artifacts": Phrases common in ChatGPT/Claude templates (e.g., "I am writing to formally confirm...", "delighted to offer you...").
   - "Placeholder Gaps": Specific dates or values that look like model-generated hallucinations.
   - "Contextual Drift": Inconsistencies in professional tone.

Output strictly a JSON object with:
{
  "verified": boolean,
  "confidenceScore": number (0-100),
  "documentType": "Offer Letter" | "Payslip" | "Experience Letter" | "Unknown",
  "authenticityAudit": {
     "isLikelyAI": boolean,
     "aiDetectionReasoning": "Specific linguistic indicators that suggest the text was generated by an LLM like GPT-4 or Claude.",
     "deepfakeConfidence": number (0-100)
  },
  "reasoning": "1-2 sentence final verdict on employment proof."
}
    `;

    console.log(`[SECURE VAULT] Running Groq Forensic Scan...`);

    // 3. Perform the audit using Llama 3.1 70B on Groq
    const completion = await groqClient.chat.completions.create({
      model: "llama-3.1-70b-versatile",
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: "You are a secure, unbiased forensic audit AI. Output JSON only." },
        { role: "user", content: prompt },
      ],
      temperature: 0, 
    });

    const verificationResult = JSON.parse(completion.choices[0].message.content || "{}");

    // Force failure if AI-generation probability is too high
    if (verificationResult.authenticityAudit?.deepfakeConfidence > 80) {
      verificationResult.verified = false;
      verificationResult.reasoning = "FORENSIC WARNING: This document contains strong linguistic signatures of synthetic AI generation (Deepfake). Record rejected.";
    }

    const endTime = Date.now();
    console.log(`[SECURE VAULT END] Audit Result: ${verificationResult.verified} | Time: ${(endTime - startTime) / 1000}s`);
    console.log(`===========================================\n`);

    return NextResponse.json(verificationResult);

  } catch (error: any) {
    console.error(`[SECURE VAULT FATAL]`, error);
    return NextResponse.json({ error: "Audit failed", details: error.message }, { status: 500 });
  }
}