// types/candidate.ts

import { Timestamp } from "firebase/firestore";

/**
 * 1. The Skill Evidence Model
 * We don't just say "They know React." We prove it.
 */
export interface SkillEvidence {
  skillName: string;          // e.g., "Next.js", "Python", "System Design"
  category: "Frontend" | "Backend" | "DevOps" | "Data" | "Algorithms" | "SoftSkill";
  proficiencyLevel: number;   // 1-100, calculated by AI based on complexity of work
  evidenceUrls: string[];     // Links to specific GitHub repos, PRs, or LeetCode submissions
  lastUsedDate: Timestamp;    // To determine if the skill is fresh or outdated
}

/**
 * 2. Platform Specific Metrics (Raw Data)
 * We store the raw data so recruiters can see the hard numbers.
 */
export interface PlatformMetrics {
  github?: {
    username: string;
    totalCommitsLastYear: number;
    totalStars: number;
    topLanguages: Record<string, number>; // e.g., { "TypeScript": 85000, "Rust": 12000 }
    openSourceContributions: number;
  };
  leetcode?: {
    username: string;
    problemsSolved: { easy: number; medium: number; hard: number };
    contestRating: number;
    globalRanking: number;
  };
  portfolio?: {
    url: string;
    hasLiveProjects: boolean;
    hasCaseStudies: boolean;
  };
}

/**
 * 3. The AI Talent Graph (The Core B2B Value Proposition)
 * This is generated by OpenAI analyzing the raw platform metrics and resumes.
 */
export interface AITalentGraph {
  learningVelocity: number;       // 0-100: How fast they pick up new, complex tech
  codeQualityScore: number;       // 0-100: Based on GitHub repo structure, testing, and docs
  problemSolvingScore: number;    // 0-100: Based on LeetCode Hards and algorithmic projects
  hiddenStrengths: string[];      // Skills they possess but didn't put on their resume
  aiSummary: string;              // A 2-sentence executive summary for the recruiter
}

/**
 * 4. The Master Candidate Profile
 * This is what lives in the 'user_profiles' collection in Firestore.
 */
export interface CandidateProfile {
  id: string;                 // Firebase Auth UID
  personalInfo: {
    fullName: string;
    email: string;
    location: string;
    willingToRelocate: boolean;
    currentRole: string;
    yearsOfExperience: number;
  };
  metrics: PlatformMetrics;
  skillGraph: SkillEvidence[];
  aiTalentGraph: AITalentGraph;
  
  // System Fields
  isActivelyLooking: boolean;
  lastSyncedAt: Timestamp;     // When the AI last scraped their GitHub/LeetCode
}